### ISSUE TITLE
Small fix for create-initrd.sh

### ISSUE THREAD

**Issue by ghost** [aweeraman/kernel-utils#1]
Your ["Build a tiny linux kernel"](https://weeraman.com/building-a-tiny-linux-kernel-8c07579ae79d) tutorial worked great, thank you for that!

I had to change the create-initrd.sh script a bit: Because stdout and sterr were written to the logs, I could not see that the busybox make command prompted for user input.

![image](https://user-images.githubusercontent.com/11392207/107847059-b9ae9a00-6de8-11eb-85b4-b57dd20de6b8.png)
etc.

Perhaps change

```
  make -j${procs} >> ${basedir}/log 2>&1
  make CONFIG_PREFIX=${initrd} install >> ${basedir}/log 2>&1
```
to

```
  make -j${procs}
  make CONFIG_PREFIX=${initrd} install
```

or use `tee` to write both to stdout and the logs

**Comment by aweeraman** [comment]
Thanks for reporting the issue
